import React from "react";
import Link from "next/link";
import Image from "next/image";


const ProductList = ({ products }) => {
  if (!Array.isArray(products)) {
    return <div>Products data is not available</div>;
  }


//  const products = [
//     {
//       id: 1,
//       title: 'Essence Mascara Lash Princess',
//       description: 'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
//       category: 'beauty',
//       price: 9.99,
//       discountPercentage: 7.17,
//       rating: 4.94,
//       stock: 5,
//       tags: [Array],
//       brand: 'Essence',
//       sku: 'RCH45Q1A',
//       weight: 2,
//       dimensions: [Object],
//       warrantyInformation: '1 month warranty',
//       shippingInformation: 'Ships in 1 month',
//       availabilityStatus: 'Low Stock',
//       reviews: [Array],
//       returnPolicy: '30 days return policy',
//       minimumOrderQuantity: 24,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/beauty/Essence%20Mascara%20Lash%20Princess/thumbnail.png'
//     },
//     {
//       id: 2,
//       title: 'Eyeshadow Palette with Mirror',
//       description: "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.",
//       category: 'beauty',
//       price: 19.99,
//       discountPercentage: 5.5,
//       rating: 3.28,
//       stock: 44,
//       tags: [Array],
//       brand: 'Glamour Beauty',
//       sku: 'MVCFH27F',
//       weight: 3,
//       dimensions: [Object],
//       warrantyInformation: '1 year warranty',
//       shippingInformation: 'Ships in 2 weeks',
//       availabilityStatus: 'In Stock',
//       reviews: [Array],
//       returnPolicy: '30 days return policy',
//       minimumOrderQuantity: 32,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/beauty/Eyeshadow%20Palette%20with%20Mirror/thumbnail.png'
//     },
//     {
//       id: 3,
//       title: 'Powder Canister',
//       description: 'The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.',
//       category: 'beauty',
//       price: 14.99,
//       discountPercentage: 18.14,
//       rating: 3.82,
//       stock: 59,
//       tags: [Array],
//       brand: 'Velvet Touch',
//       sku: '9EN8WLT2',
//       weight: 8,
//       dimensions: [Object],
//       warrantyInformation: '2 year warranty',
//       shippingInformation: 'Ships in 1-2 business days',
//       availabilityStatus: 'In Stock',
//       reviews: [Array],
//       returnPolicy: '60 days return policy',
//       minimumOrderQuantity: 25,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/beauty/Powder%20Canister/thumbnail.png'
//     },
//     {
//       id: 4,
//       title: 'Red Lipstick',
//       description: 'The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.',
//       category: 'beauty',
//       price: 12.99,
//       discountPercentage: 19.03,
//       rating: 2.51,
//       stock: 68,
//       tags: [Array],
//       brand: 'Chic Cosmetics',
//       sku: 'O5IF1NTA',
//       weight: 5,
//       dimensions: [Object],
//       warrantyInformation: 'Lifetime warranty',
//       shippingInformation: 'Ships in 2 weeks',
//       availabilityStatus: 'In Stock',
//       reviews: [Array],
//       returnPolicy: '90 days return policy',
//       minimumOrderQuantity: 6,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/beauty/Red%20Lipstick/thumbnail.png'
//     },
//     {
//       id: 5,
//       title: 'Red Nail Polish',
//       description: 'The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.',
//       category: 'beauty',
//       price: 8.99,
//       discountPercentage: 2.46,
//       rating: 3.91,
//       stock: 71,
//       tags: [Array],
//       brand: 'Nail Couture',
//       sku: 'YUIIIP4W',
//       weight: 9,
//       dimensions: [Object],
//       warrantyInformation: '1 year warranty',
//       shippingInformation: 'Ships in 1 week',
//       availabilityStatus: 'In Stock',
//       reviews: [Array],
//       returnPolicy: 'No return policy',
//       minimumOrderQuantity: 46,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/beauty/Red%20Nail%20Polish/thumbnail.png'
//     },
//     {
//       id: 6,
//       title: 'Calvin Klein CK One',
//       description: "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear.",
//       category: 'fragrances',
//       price: 49.99,
//       discountPercentage: 0.32,
//       rating: 4.85,
//       stock: 17,
//       tags: [Array],
//       brand: 'Calvin Klein',
//       sku: 'DZM2JQZE',
//       weight: 5,
//       dimensions: [Object],
//       warrantyInformation: '5 year warranty',
//       shippingInformation: 'Ships overnight',
//       availabilityStatus: 'In Stock',
//       reviews: [Array],
//       returnPolicy: 'No return policy',
//       minimumOrderQuantity: 20,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/thumbnail.png'
//     },
//     {
//       id: 7,
//       title: 'Chanel Coco Noir Eau De',
//       description: 'Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.',
//       category: 'fragrances',
//       price: 129.99,
//       discountPercentage: 18.64,
//       rating: 2.76,
//       stock: 41,
//       tags: [Array],
//       brand: 'Chanel',
//       sku: 'K71HBCGS',
//       weight: 4,
//       dimensions: [Object],
//       warrantyInformation: '1 week warranty',
//       shippingInformation: 'Ships in 1 month',
//       availabilityStatus: 'In Stock',
//       reviews: [Array],
//       returnPolicy: '60 days return policy',
//       minimumOrderQuantity: 5,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/thumbnail.png'
//     },
//     {
//       id: 8,
//       title: "Dior J'adore",
//       description: "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.",
//       category: 'fragrances',
//       price: 89.99,
//       discountPercentage: 17.44,
//       rating: 3.31,
//       stock: 91,
//       tags: [Array],
//       brand: 'Dior',
//       sku: 'E70NB03B',
//       weight: 10,
//       dimensions: [Object],
//       warrantyInformation: 'Lifetime warranty',
//       shippingInformation: 'Ships in 2 weeks',
//       availabilityStatus: 'In Stock',
//       reviews: [Array],
//       returnPolicy: '7 days return policy',
//       minimumOrderQuantity: 8,
//       meta: [Object],
//       images: [Array],
//       thumbnail: "https://cdn.dummyjson.com/products/images/fragrances/Dior%20J'adore/thumbnail.png"
//     },
//     {
//       id: 9,
//       title: 'Dolce Shine Eau de',
//       description: "Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It's a joyful and youthful scent.",
//       category: 'fragrances',
//       price: 69.99,
//       discountPercentage: 11.47,
//       rating: 2.68,
//       stock: 3,
//       tags: [Array],
//       brand: 'Dolce & Gabbana',
//       sku: '1NBFK980',
//       weight: 5,
//       dimensions: [Object],
//       warrantyInformation: '5 year warranty',
//       shippingInformation: 'Ships in 1-2 business days',
//       availabilityStatus: 'Low Stock',
//       reviews: [Array],
//       returnPolicy: '30 days return policy',
//       minimumOrderQuantity: 9,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/fragrances/Dolce%20Shine%20Eau%20de/thumbnail.png'
//     },
//     {
//       id: 10,
//       title: 'Gucci Bloom Eau de',
//       description: "Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It's a modern and romantic scent.",
//       category: 'fragrances',
//       price: 79.99,
//       discountPercentage: 8.9,
//       rating: 2.69,
//       stock: 93,
//       tags: [Array],
//       brand: 'Gucci',
//       sku: 'FFKZ6HOF',
//       weight: 10,
//       dimensions: [Object],
//       warrantyInformation: 'No warranty',
//       shippingInformation: 'Ships in 2 weeks',
//       availabilityStatus: 'In Stock',
//       reviews: [Array],
//       returnPolicy: 'No return policy',
//       minimumOrderQuantity: 10,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/fragrances/Gucci%20Bloom%20Eau%20de/thumbnail.png'
//     },
//     {
//       id: 11,
//       title: 'Annibale Colombo Bed',
//       description: 'The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.',
//       category: 'furniture',
//       price: 1899.99,
//       discountPercentage: 0.29,
//       rating: 4.14,
//       stock: 47,
//       tags: [Array],
//       brand: 'Annibale Colombo',
//       sku: '4KMDTZWF',
//       weight: 3,
//       dimensions: [Object],
//       warrantyInformation: '2 year warranty',
//       shippingInformation: 'Ships overnight',
//       availabilityStatus: 'In Stock',
//       reviews: [Array],
//       returnPolicy: '7 days return policy',
//       minimumOrderQuantity: 1,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Bed/thumbnail.png'
//     },
//     {
//       id: 12,
//       title: 'Annibale Colombo Sofa',
//       description: 'The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.',
//       category: 'furniture',
//       price: 2499.99,
//       discountPercentage: 18.54,
//       rating: 3.08,
//       stock: 16,
//       tags: [Array],
//       brand: 'Annibale Colombo',
//       sku: 'LUU95CQP',
//       weight: 3,
//       dimensions: [Object],
//       warrantyInformation: '1 month warranty',
//       shippingInformation: 'Ships overnight',
//       availabilityStatus: 'In Stock',
//       reviews: [Array],
//       returnPolicy: '7 days return policy',
//       minimumOrderQuantity: 1,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Sofa/thumbnail.png'
//     },
//     {
//       id: 13,
//       title: 'Bedside Table African Cherry',
//       description: 'The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.',
//       category: 'furniture',
//       price: 299.99,
//       discountPercentage: 9.58,
//       rating: 4.48,
//       stock: 16,
//       tags: [Array],
//       brand: 'Furniture Co.',
//       sku: 'OWPLTZYX',
//       weight: 10,
//       dimensions: [Object],
//       warrantyInformation: '6 months warranty',
//       shippingInformation: 'Ships in 1-2 business days',
//       availabilityStatus: 'In Stock',
//       reviews: [Array],
//       returnPolicy: 'No return policy',
//       minimumOrderQuantity: 5,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/furniture/Bedside%20Table%20African%20Cherry/thumbnail.png'
//     },
//     {
//       id: 14,
//       title: 'Knoll Saarinen Executive Conference Chair',
//       description: 'The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.',
//       category: 'furniture',
//       price: 499.99,
//       discountPercentage: 15.23,
//       rating: 4.11,
//       stock: 47,
//       tags: [Array],
//       brand: 'Knoll',
//       sku: 'RKHVJ4FE',
//       weight: 3,
//       dimensions: [Object],
//       warrantyInformation: 'Lifetime warranty',
//       shippingInformation: 'Ships in 3-5 business days',
//       availabilityStatus: 'In Stock',
//       reviews: [Array],
//       returnPolicy: '30 days return policy',
//       minimumOrderQuantity: 5,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/furniture/Knoll%20Saarinen%20Executive%20Conference%20Chair/thumbnail.png'
//     },
//     {
//       id: 15,
//       title: 'Wooden Bathroom Sink With Mirror',
//       description: 'The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.',
//       category: 'furniture',
//       price: 799.99,
//       discountPercentage: 11.22,
//       rating: 3.26,
//       stock: 95,
//       tags: [Array],
//       brand: 'Bath Trends',
//       sku: '7OLTIEVO',
//       weight: 6,
//       dimensions: [Object],
//       warrantyInformation: '6 months warranty',
//       shippingInformation: 'Ships in 3-5 business days',
//       availabilityStatus: 'In Stock',
//       reviews: [Array],
//       returnPolicy: '7 days return policy',
//       minimumOrderQuantity: 1,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/furniture/Wooden%20Bathroom%20Sink%20With%20Mirror/thumbnail.png'
//     },
//     {
//       id: 16,
//       title: 'Apple',
//       description: 'Fresh and crisp apples, perfect for snacking or incorporating into various recipes.',
//       category: 'groceries',
//       price: 1.99,
//       discountPercentage: 1.97,
//       rating: 2.96,
//       stock: 9,
//       tags: [Array],
//       sku: 'QTROUV79',
//       weight: 8,
//       dimensions: [Object],
//       warrantyInformation: '2 year warranty',
//       shippingInformation: 'Ships in 2 weeks',
//       availabilityStatus: 'In Stock',
//       reviews: [Array],
//       returnPolicy: '60 days return policy',
//       minimumOrderQuantity: 44,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/groceries/Apple/thumbnail.png'
//     },
//     {
//       id: 17,
//       title: 'Beef Steak',
//       description: 'High-quality beef steak, great for grilling or cooking to your preferred level of doneness.',
//       category: 'groceries',
//       price: 12.99,
//       discountPercentage: 17.99,
//       rating: 2.83,
//       stock: 96,
//       tags: [Array],
//       sku: 'BWWA2MSO',
//       weight: 9,
//       dimensions: [Object],
//       warrantyInformation: '1 month warranty',
//       shippingInformation: 'Ships overnight',
//       availabilityStatus: 'In Stock',
//       reviews: [Array],
//       returnPolicy: '90 days return policy',
//       minimumOrderQuantity: 21,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/groceries/Beef%20Steak/thumbnail.png'
//     },
//     {
//       id: 18,
//       title: 'Cat Food',
//       description: 'Nutritious cat food formulated to meet the dietary needs of your feline friend.',
//       category: 'groceries',
//       price: 8.99,
//       discountPercentage: 9.57,
//       rating: 2.88,
//       stock: 13,
//       tags: [Array],
//       sku: 'C3F8QN6O',
//       weight: 9,
//       dimensions: [Object],
//       warrantyInformation: '3 months warranty',
//       shippingInformation: 'Ships in 1-2 business days',
//       availabilityStatus: 'In Stock',
//       reviews: [Array],
//       returnPolicy: '7 days return policy',
//       minimumOrderQuantity: 48,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/groceries/Cat%20Food/thumbnail.png'
//     },
//     {
//       id: 19,
//       title: 'Chicken Meat',
//       description: 'Fresh and tender chicken meat, suitable for various culinary preparations.',
//       category: 'groceries',
//       price: 9.99,
//       discountPercentage: 10.46,
//       rating: 4.61,
//       stock: 69,
//       tags: [Array],
//       sku: 'G5YEHW7B',
//       weight: 7,
//       dimensions: [Object],
//       warrantyInformation: 'Lifetime warranty',
//       shippingInformation: 'Ships in 1 month',
//       availabilityStatus: 'In Stock',
//       reviews: [Array],
//       returnPolicy: '7 days return policy',
//       minimumOrderQuantity: 46,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/groceries/Chicken%20Meat/thumbnail.png'
//     },
//     {
//       id: 20,
//       title: 'Cooking Oil',
//       description: 'Versatile cooking oil suitable for frying, sautéing, and various culinary applications.',
//       category: 'groceries',
//       price: 4.99,
//       discountPercentage: 18.89,
//       rating: 4.01,
//       stock: 22,
//       tags: [Array],
//       sku: 'Q6ZP1UY8',
//       weight: 8,
//       dimensions: [Object],
//       warrantyInformation: 'Lifetime warranty',
//       shippingInformation: 'Ships in 1 month',
//       availabilityStatus: 'In Stock',
//       reviews: [Array],
//       returnPolicy: '60 days return policy',
//       minimumOrderQuantity: 2,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/groceries/Cooking%20Oil/thumbnail.png'
//     },
//     {
//       id: 21,
//       title: 'Cucumber',
//       description: 'Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.',
//       category: 'groceries',
//       price: 1.49,
//       discountPercentage: 11.44,
//       rating: 4.71,
//       stock: 22,
//       tags: [Array],
//       sku: '6KGF2K6Z',
//       weight: 9,
//       dimensions: [Object],
//       warrantyInformation: '5 year warranty',
//       shippingInformation: 'Ships overnight',
//       availabilityStatus: 'In Stock',
//       reviews: [Array],
//       returnPolicy: '30 days return policy',
//       minimumOrderQuantity: 7,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/groceries/Cucumber/thumbnail.png'
//     },
//     {
//       id: 22,
//       title: 'Dog Food',
//       description: 'Specially formulated dog food designed to provide essential nutrients for your canine companion.',
//       category: 'groceries',
//       price: 10.99,
//       discountPercentage: 18.15,
//       rating: 2.74,
//       stock: 40,
//       tags: [Array],
//       sku: 'A6QRCH37',
//       weight: 2,
//       dimensions: [Object],
//       warrantyInformation: '1 year warranty',
//       shippingInformation: 'Ships in 1 month',
//       availabilityStatus: 'In Stock',
//       reviews: [Array],
//       returnPolicy: '90 days return policy',
//       minimumOrderQuantity: 29,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/groceries/Dog%20Food/thumbnail.png'
//     },
//     {
//       id: 23,
//       title: 'Eggs',
//       description: 'Fresh eggs, a versatile ingredient for baking, cooking, or breakfast.',
//       category: 'groceries',
//       price: 2.99,
//       discountPercentage: 5.8,
//       rating: 4.46,
//       stock: 10,
//       tags: [Array],
//       sku: 'YA617RI7',
//       weight: 4,
//       dimensions: [Object],
//       warrantyInformation: '3 year warranty',
//       shippingInformation: 'Ships overnight',
//       availabilityStatus: 'In Stock',
//       reviews: [Array],
//       returnPolicy: '30 days return policy',
//       minimumOrderQuantity: 43,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/groceries/Eggs/thumbnail.png'
//     },
//     {
//       id: 24,
//       title: 'Fish Steak',
//       description: 'Quality fish steak, suitable for grilling, baking, or pan-searing.',
//       category: 'groceries',
//       price: 14.99,
//       discountPercentage: 7,
//       rating: 4.83,
//       stock: 99,
//       tags: [Array],
//       sku: 'XNIH1MTA',
//       weight: 8,
//       dimensions: [Object],
//       warrantyInformation: '1 year warranty',
//       shippingInformation: 'Ships in 1 month',
//       availabilityStatus: 'In Stock',
//       reviews: [Array],
//       returnPolicy: '30 days return policy',
//       minimumOrderQuantity: 49,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/groceries/Fish%20Steak/thumbnail.png'
//     },
//     {
//       id: 25,
//       title: 'Green Bell Pepper',
//       description: 'Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes.',
//       category: 'groceries',
//       price: 1.29,
//       discountPercentage: 15.5,
//       rating: 4.28,
//       stock: 89,
//       tags: [Array],
//       sku: 'HU7S7VQ0',
//       weight: 7,
//       dimensions: [Object],
//       warrantyInformation: '5 year warranty',
//       shippingInformation: 'Ships overnight',
//       availabilityStatus: 'In Stock',
//       reviews: [Array],
//       returnPolicy: '30 days return policy',
//       minimumOrderQuantity: 1,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/groceries/Green%20Bell%20Pepper/thumbnail.png'
//     },
//     {
//       id: 26,
//       title: 'Green Chili Pepper',
//       description: 'Spicy green chili pepper, ideal for adding heat to your favorite recipes.',
//       category: 'groceries',
//       price: 0.99,
//       discountPercentage: 18.51,
//       rating: 4.43,
//       stock: 8,
//       tags: [Array],
//       sku: 'Y4RM3JCB',
//       weight: 2,
//       dimensions: [Object],
//       warrantyInformation: 'No warranty',
//       shippingInformation: 'Ships in 1-2 business days',
//       availabilityStatus: 'In Stock',
//       reviews: [Array],
//       returnPolicy: '30 days return policy',
//       minimumOrderQuantity: 43,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/groceries/Green%20Chili%20Pepper/thumbnail.png'
//     },
//     {
//       id: 27,
//       title: 'Honey Jar',
//       description: 'Pure and natural honey in a convenient jar, perfect for sweetening beverages or drizzling over food.',
//       category: 'groceries',
//       price: 6.99,
//       discountPercentage: 1.91,
//       rating: 3.5,
//       stock: 25,
//       tags: [Array],
//       sku: 'BTBNIIOU',
//       weight: 9,
//       dimensions: [Object],
//       warrantyInformation: '2 year warranty',
//       shippingInformation: 'Ships overnight',
//       availabilityStatus: 'In Stock',
//       reviews: [Array],
//       returnPolicy: '90 days return policy',
//       minimumOrderQuantity: 1,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/groceries/Honey%20Jar/thumbnail.png'
//     },
//     {
//       id: 28,
//       title: 'Ice Cream',
//       description: 'Creamy and delicious ice cream, available in various flavors for a delightful treat.',
//       category: 'groceries',
//       price: 5.49,
//       discountPercentage: 7.58,
//       rating: 3.77,
//       stock: 76,
//       tags: [Array],
//       sku: 'VEZMU1EQ',
//       weight: 5,
//       dimensions: [Object],
//       warrantyInformation: '2 year warranty',
//       shippingInformation: 'Ships in 2 weeks',
//       availabilityStatus: 'In Stock',
//       reviews: [Array],
//       returnPolicy: 'No return policy',
//       minimumOrderQuantity: 19,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/groceries/Ice%20Cream/thumbnail.png'
//     },
//     {
//       id: 29,
//       title: 'Juice',
//       description: 'Refreshing fruit juice, packed with vitamins and great for staying hydrated.',
//       category: 'groceries',
//       price: 3.99,
//       discountPercentage: 5.45,
//       rating: 3.41,
//       stock: 99,
//       tags: [Array],
//       sku: 'M2K19S06',
//       weight: 2,
//       dimensions: [Object],
//       warrantyInformation: '1 week warranty',
//       shippingInformation: 'Ships in 1-2 business days',
//       availabilityStatus: 'In Stock',
//       reviews: [Array],
//       returnPolicy: '90 days return policy',
//       minimumOrderQuantity: 26,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/groceries/Juice/thumbnail.png'
//     },
//     {
//       id: 30,
//       title: 'Kiwi',
//       description: 'Nutrient-rich kiwi, perfect for snacking or adding a tropical twist to your dishes.',
//       category: 'groceries',
//       price: 2.49,
//       discountPercentage: 10.32,
//       rating: 4.37,
//       stock: 1,
//       tags: [Array],
//       sku: '0X3NORB9',
//       weight: 8,
//       dimensions: [Object],
//       warrantyInformation: '6 months warranty',
//       shippingInformation: 'Ships in 3-5 business days',
//       availabilityStatus: 'Low Stock',
//       reviews: [Array],
//       returnPolicy: '7 days return policy',
//       minimumOrderQuantity: 8,
//       meta: [Object],
//       images: [Array],
//       thumbnail: 'https://cdn.dummyjson.com/products/images/groceries/Kiwi/thumbnail.png'
//     }
//   ]



  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
      {products.map((product) => (
        <Link key={product.id} href={`/${product.id}`}>
          <div className="border  p-4 rounded-lg shadow-md hover:shadow-lg  flex flex-col gap-4  cursor-pointer relative">
            <p className=" absolute top-3 right-4 p-0.5 bg-green-500 text-xs text-white z-10 ">
              -{product.discountPercentage} %
            </p>
            <div className="size-60 relative w-5/6 mx-auto ">
              <Image
                src={product.thumbnail}
                alt={product.title}
                fill
                className="object-cover rounded"
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              />
            </div>
            <div>
              <p className="text-gray-400 text-xs mb-2 ">{product.category}</p>
              <p className="text-base font-medium mb-2">{product.title}</p>

              <p className="text-[#333333]  text-sm font-bold mb-1">
                $
                {(
                  product.price -
                  (product.price * product.discountPercentage) / 100
                ).toFixed(2)}
              </p>
              <p className="text-gray-400 text-sm line-through">
                ${product.price}
              </p>
            </div>

            
              <button className="bg-blue-800 text-white rounded-lg py-2.5 w-full mx-auto border border-transparent hover:bg-transparent hover:text-[#333333] hover:border-gray-300 hover:border-2">
                View
              </button>
            
          </div>
        </Link>
      ))}
    </div>
  );
};

export default ProductList;
